  wallpaper {
    monitor = eDP-1
    path = /home/kurokaiden/dotfiles/Wallpapers/tron-ares.jpg
    fit_mode = cover
  }

  wallpaper {
    monitor = HDMI-A-1
    path = /home/kurokaiden/dotfiles/Wallpapers/tron-ares.jpg
    fit_mode = cover
  }
 
  splash = false
